# Generated by Django 4.2.11 on 2024-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
